import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    // Must come before the React plugin so route files are transformed first
    tanstackRouter({
      target: "react",
      autoCodeSplitting: true,
      routeTreeFileHeader: [
        "/* eslint-disable */",
        "// @ts-nocheck",
        "// biome-ignore-all lint: generated by @tanstack/router-plugin",
        "// biome-ignore-all format: generated by @tanstack/router-plugin",
        "// biome-ignore-all assist/source/organizeImports: generated by @tanstack/router-plugin",
      ],
    }),
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  server: {
    proxy: {
      // API + WS go to the Hono server in dev; in prod the server serves the SPA itself
      "/api": {
        target: "http://localhost:3000",
        ws: true,
      },
    },
  },
});
