import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import pkg from "./package.json" with { type: "json" };

// release-please bumps package.json on each release; surface it in the UI footer.
// "0.0.0" is the un-released placeholder, so show a friendlier "dev" until a real
// version is cut.
const appVersion = pkg.version && pkg.version !== "0.0.0" ? pkg.version : "dev";

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(appVersion),
  },
  plugins: [
    // Must come before the React plugin so route files are transformed first
    tanstackRouter({
      target: "react",
      autoCodeSplitting: true,
      routeTreeFileHeader: [
        "/* eslint-disable */",
        "// @ts-nocheck",
        "// biome-ignore-all lint: generated by @tanstack/router-plugin",
        "// biome-ignore-all format: generated by @tanstack/router-plugin",
        "// biome-ignore-all assist/source/organizeImports: generated by @tanstack/router-plugin",
      ],
    }),
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  server: {
    proxy: {
      // API + WS go to the Hono server in dev; in prod the server serves the SPA itself
      "/api": {
        target: "http://localhost:3000",
        ws: true,
      },
    },
  },
});
